"""
API documentation / route-listing routes.
=========================================
Exposes the FastAPI route table in three forms:

  GET /routes      — Plain HTML list grouped by tag/prefix (debug-friendly)
  GET /api/routes  — JSON, same grouping (consumed by /api-docs UI)
  GET /api-docs    — Serves the interactive API explorer (static/api-docs.html)

Grouping rules (FastAPI does not have Flask's blueprint endpoint prefix,
so we derive a group label per route):

  1. If the route has tags (set via APIRouter(tags=[...]) or @app.get(..., tags=[...]))
     → use the first tag as the group name.
  2. Otherwise, infer from the URL path:
       /api/<group>/...        → "<group>"
       /<group>                → "<group>"
       /                       → "general"
       any other shape         → "general"

  3. Routes whose group resolves to one of HIDDEN_GROUPS are excluded entirely
     (e.g. internal websocket transport, static mounts).
"""
import logging
import urllib.parse
from collections import defaultdict
from pathlib import Path

from fastapi import FastAPI
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse
from fastapi.routing import APIRoute

logger = logging.getLogger("routes.api_docs")

# Methods we never display — they're auto-generated by FastAPI/Starlette
HIDDEN_METHODS = {"HEAD", "OPTIONS"}

# Endpoint groups to hide from the docs (still callable, just not listed)
HIDDEN_GROUPS = {"static"}

# Path prefixes that should never appear in the docs
HIDDEN_PATH_PREFIXES = ("/static/", "/ws")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _group_for_route(route: APIRoute) -> str:
    """
    Decide which group label a route belongs to.

    Priority: tags first, then URL-path inference.
    """
    tags = getattr(route, "tags", None) or []
    if tags:
        return str(tags[0]).lower().replace(" ", "_")

    path = route.path or "/"

    # /api/foo/bar  →  "foo"
    if path.startswith("/api/"):
        rest = path[len("/api/"):].split("/", 1)[0]
        return rest.lower() if rest else "general"

    # /foo  →  "foo"
    parts = [p for p in path.split("/") if p]
    if parts:
        return parts[0].lower()

    return "general"


def _is_hidden(route: APIRoute, group: str) -> bool:
    if group in HIDDEN_GROUPS:
        return True
    if any(route.path.startswith(p) for p in HIDDEN_PATH_PREFIXES):
        return True
    # FastAPI's own auto-generated docs endpoints if enabled
    if route.path in ("/openapi.json", "/docs", "/redoc",
                      "/docs/oauth2-redirect"):
        return True
    return False


def _iter_documented_routes(app: FastAPI):
    """
    Yield (group, method, path) tuples for every documentable route.
    """
    for route in app.routes:
        # Only care about HTTP routes — skip WebSocketRoute, Mount, etc.
        if not isinstance(route, APIRoute):
            continue

        group = _group_for_route(route)
        if _is_hidden(route, group):
            continue

        path = urllib.parse.unquote(route.path or "/")
        methods = sorted(
            m for m in (route.methods or set())
            if m not in HIDDEN_METHODS
        )
        for method in methods:
            yield group, method, path


# ---------------------------------------------------------------------------
# Registration
# ---------------------------------------------------------------------------

def register_api_docs_routes(app: FastAPI):
    """Register the /routes, /api/routes and /api-docs endpoints."""

    @app.get("/routes", response_class=HTMLResponse, include_in_schema=False)
    async def list_routes_html():
        """Plain HTML route listing, grouped by tag/prefix."""
        grouped = defaultdict(list)
        for group, method, path in _iter_documented_routes(app):
            safe_path = path.replace("<", "&lt;").replace(">", "&gt;")
            grouped[group].append((method, safe_path))

        out = [
            "<!DOCTYPE html><html><head><meta charset='utf-8'>",
            "<title>ZMM Routes</title>",
            "<style>",
            "body{font-family:'Segoe UI',sans-serif;background:#0f172a;color:#e5e7eb;",
            "padding:20px;max-width:1100px;margin:auto;}",
            "h1{color:#3b82f6;}h2{color:#60a5fa;border-bottom:1px solid #1f2937;",
            "padding-bottom:4px;margin-top:28px;}",
            "pre{background:#1f2937;padding:12px;border-radius:6px;",
            "border:1px solid #374151;overflow-x:auto;}",
            "a{color:#60a5fa;}",
            "</style></head><body>",
            "<h1>ZigBee &amp; Matter Manager — Routes</h1>",
            "<p>For the interactive explorer see <a href='/api-docs'>/api-docs</a>.</p>",
        ]

        for group in sorted(grouped.keys()):
            entries = sorted(grouped[group], key=lambda mp: mp[1])
            out.append(f"<h2>{group.replace('_', ' ').title()}</h2>")
            out.append("<pre>")
            for method, path in entries:
                # Group multiple methods on one line if same path repeats
                out.append(f"{method:<7} {path}")
            out.append("</pre>")

        out.append("</body></html>")
        return HTMLResponse("\n".join(out))

    @app.get("/api/routes", include_in_schema=False)
    async def list_routes_json():
        """JSON route listing — consumed by the /api-docs UI."""
        grouped = defaultdict(list)
        for group, method, path in _iter_documented_routes(app):
            grouped[group].append({"method": method, "path": path})

        # Sort each group's entries by path
        for g in grouped:
            grouped[g].sort(key=lambda r: (r["path"], r["method"]))

        # Sort groups alphabetically
        return JSONResponse(dict(sorted(grouped.items())))

    @app.get("/api-docs", response_class=HTMLResponse, include_in_schema=False)
    async def api_docs_page():
        """Serve the interactive API explorer."""
        path = Path("static/api-docs.html")
        if not path.exists():
            return HTMLResponse(
                "<h1>api-docs.html missing</h1>"
                "<p>Expected at <code>static/api-docs.html</code>.</p>",
                status_code=404,
            )
        return FileResponse(str(path))

    logger.info("API docs routes registered (/routes, /api/routes, /api-docs)")